<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/array_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Slicing an array

In [1]:
import numpy as np

In [19]:
# slicing 1D array
arr1 = np.arange(2, 20, 2)
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
# slicing
sliced_arr1 = arr1[1:4]
sliced_arr1

array([4, 6, 8])

In [9]:
# changing sliced array
sliced_arr1[:] = 1
arr1

array([ 2,  1,  1,  1, 10, 12, 14, 16, 18])

In [14]:
# copying a sliced array
sliced_arr1c = arr1[-3:].copy()
sliced_arr1c

array([14, 16, 18])

In [16]:
# changing only copied slice
sliced_arr1c[:] = 0
print(sliced_arr1c)
print(arr1)

[0 0 0]
[ 2  1  1  1 10 12 14 16 18]


In [21]:
# slicing 2D array
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]]) # 3:3 2D array
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
sliced_arr2 = arr2[1, 1:3]
sliced_arr2

array([5, 6])

In [34]:
# slicing 3D array
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
         [[10,11,12],[13,14,15],[16,17,18]],
         [[19,20,21],[22,23,24],[25,26,27]]])

arr3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [61]:
sliced_arr3 = arr3[2][0][1:]
print(sliced_arr3)

[20 21]
