<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/array_data_types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Types in arrays

#declaring data type while creating an array

In [3]:
import numpy as np


In [4]:
# defining data type of an array.
arrd = np.array([1, 2, 3], dtype=np.float32)
print(arrd)
print(arrd.dtype)

[1. 2. 3.]
float32


#altering data type

In [5]:
# creating an array with float64 elelments
arrf = np.array([1.3, 7.8, 3.14], dtype=np.float64)
print(arrf)
print(arrf.dtype)

[1.3  7.8  3.14]
float64


In [8]:
# converting float64 to int32 by astype function
arri = arrf.astype(np.int64)
print(arri)
print(arri.dtype)

[1 7 3]
int64
