<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Boolean indexing

In [12]:
import numpy as np

In [10]:
# names array
names = np.array(["alijon","asadbek",'diyor','valijon','alijon','asadbek'])
names

array(['alijon', 'asadbek', 'diyor', 'valijon', 'alijon', 'asadbek'],
      dtype='<U7')

In [4]:
names == 'alijon'

array([ True, False, False, False,  True, False])

In [18]:
data = np.random.randn(6,4) # generating 7x4 array with random info
data


array([[-1.05195754, -1.6321563 ,  0.23778413,  1.04289094],
       [ 0.06081532,  0.84294521, -0.95335383,  0.26021757],
       [ 0.88899176, -1.31183781,  2.52164969,  0.04194128],
       [-1.27694943, -1.50231127,  0.89385309,  0.24198407],
       [-0.91229706, -0.06946103, -1.71360665, -1.87398016],
       [ 0.05962757,  0.62217337,  0.03832834,  1.50767646]])

In [19]:
# slicing an appropriate values by condition
data[names == "alijon"]

array([[-1.05195754, -1.6321563 ,  0.23778413,  1.04289094],
       [-0.91229706, -0.06946103, -1.71360665, -1.87398016]])

In [24]:
# slicing by two condition
data[(names == "alijon") |  (names == 'diyor'), :2]

array([[-1.05195754, -1.6321563 ],
       [ 0.88899176, -1.31183781],
       [-0.91229706, -0.06946103]])

In [27]:
# replacing a specific valus by contion
data[ data < 0 ] = 0 # replacing minus values with zeros
data

array([[0.        , 0.        , 0.23778413, 1.04289094],
       [0.06081532, 0.84294521, 0.        , 0.26021757],
       [0.88899176, 0.        , 2.52164969, 0.04194128],
       [0.        , 0.        , 0.89385309, 0.24198407],
       [0.        , 0.        , 0.        , 0.        ],
       [0.05962757, 0.62217337, 0.03832834, 1.50767646]])

#Just task

In [42]:
names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
data = np.array([[5, 6, 1, 1],
   [9, 1, 1, 1],
   [7, 7, 4, 2],
   [1, 5, 1, 9],
   [9, 9, 4, 5],
   [7, 5, 9, 6],
   [5, 3, 7, 4]])
data2 = (names =='Javohir') | (names == 'Elyor')
data[data2]


array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])