<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/conditions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conditional operators

In [1]:
import numpy as np

In [2]:
# using where operator
arr1 = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
arr2 = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

condition = np.array([True, False, False, True, True]) # declaring a condition
result = np.where(condition, arr1, arr2) # if the condition is True, result == arr1, else, result == arr2
result

array([1.1, 2.2, 2.3, 1.4, 1.5])

In [4]:
# where another example
arr = np.random.randn(4, 4)
print(arr,"\n")
result_arr = np.where(arr<0, -8, 8)
result_arr


[[-0.66061618 -1.15060688 -0.36660222 -0.50084165]
 [-1.98092601 -2.00186643  0.61590177 -1.15199763]
 [-1.30889771 -0.7089416  -0.65143195 -0.19888431]
 [-0.20909948 -0.66974623  0.38089264 -2.17156569]] 



array([[-8, -8, -8, -8],
       [-8, -8,  8, -8],
       [-8, -8, -8, -8],
       [-8, -8,  8, -8]])