<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy Library

#Comparing the time of normal and vectorized processing

In [1]:
# importing numpy
import numpy as np

In [ ]:
# converting a list to an array
my_list = list(range(1, 100_001)) # list in range 1~100_000 as normap
my_array = np.array(range(1, 100_001)) # array in range 1~100_000 as vectorized

In [ ]:
# calculating normal processing time
%time for _ in range(10): [x*3 for x in my_list]

CPU times: user 85.3 ms, sys: 1.78 ms, total: 87.1 ms
Wall time: 88.7 ms


In [ ]:
# calculalting vectorized processing time
%time for _ in range(10): my_array*3

CPU times: user 4.44 ms, sys: 0 ns, total: 4.44 ms
Wall time: 7.07 ms


#Different ways of creating an array by using numpy array method





In [12]:
# converting list to array
list = [1, 2, 3, 4, 5] # list
arr1 = np.array(list) # array


In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [8]:
# converting a tuple to an array
tup = (1, 2, 4.4, 78.1) # tuple
arr2 = np.array(tup) # array

In [9]:
arr2

array([ 1. ,  2. ,  4.4, 78.1])

Dimention of an array

In [ ]:
print(arr1.ndim)
print(arr2.ndim)

1
1


# Multidimentional arrays (N-dimentional)

#Creating 2D array

In [3]:
# creating 2D array by converting nested list
list2 = [[1,2,3],[4,5,6], [7,8,9]] # nested list
arr2d = np.array(list2) # 2D array

In [4]:
print(f"nested list: {list2}")
print(f"2D array or matrix:\n {arr2d}")

nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2D array or matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# printing a specific element
print(arr2d[2,2])

9


# Creating 3D array


In [5]:
# converting list to 3D array
list3 = [[[1,2,3],[4,5,6],[7,8,9]],
 [[10,11,12],[13,14,15],[16,17,18]],
  [[19,20,21],[22,23,24],[25,26,27]]]

arr3d = np.array(list3) # 3D array

In [6]:
print(f"3 times nested list:\n {list3}")
print(f"\n3D array:\n {arr3d}")

3 times nested list:
 [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]

3D array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
# printing a certain element
print(arr3d[1,2,2])

18


#shape and size of an array

In [16]:
# printing arrays' shapes and sizes: shape = (r,c), size = the num of elements
# 1D array
print(f"1D array:\n{arr1}\n its shape: {arr1.shape}\n its size: {arr1.size}")

# 2D array
print(f"\n2D array:\n{arr2d}\n its shape: {arr2d.shape}\n its size: {arr2d.size}")

# 3D array
print(f"\n3D array:\n{arr3d}\n its shape: {arr3d.shape}\n its size: {arr3d.size}")


1D array:
[1 2 3 4 5]
 its shape: (5,)
 its size: 5

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 its shape: (3, 3)
 its size: 9

3D array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
 its shape: (3, 3, 3)
 its size: 27


#*zeros* and *ones* functions for creating an array

In [19]:
# creating 3:4 array with only zero elements by zeros function
arrz = np.zeros(shape=(3,4))
print(arrz)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
# creating 4:3 array with only one elements by ones function
arro = np.ones(shape=(4,3))
print(arro)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#arange function

In [22]:
arrarn = np.arange(1,20,2) # array with elements from 1 to 19 in 2 step
print(arrarn)

[ 1  3  5  7  9 11 13 15 17 19]
