<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/reshaping_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reshaping an array-swinging an array's axes

In [1]:
import numpy as np

In [31]:
# reshape() function
arr1 = np.arange(1, 7)
print(arr1)
arr2 = arr1.reshape(2,3)
arr2

[1 2 3 4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# transpose method
print(arr2)
print(f"\nTransposed arr:\n {arr2.T}")

[[1 2 3]
 [4 5 6]]

Transposed arr:
 [[1 4]
 [2 5]
 [3 6]]


In [15]:
# swaping an array's axes
print(arr2)
arr2.swapaxes(1,0)


[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
# creating two arrays with contrary elements
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(-9,0)
arr4r = arr4[::-1].reshape(3,3) # reversing order of elements

print(f"arr3:\n {arr3}\n\n arr4r:\n {arr4r}")

arr3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 arr4r:
 [[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]


In [51]:
# dot() function
arr_sum = np.dot(arr3, arr4r)
arr_sum

array([[ -30,  -36,  -42],
       [ -66,  -81,  -96],
       [-102, -126, -150]])

# Universal and binary functions

In [57]:
# sqrt()
print(arr3)
np.sqrt(arr3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [60]:
# add()
print(f"arr3:\n {arr3}\n arr4r:\n {arr4r}\n")
np.add(arr3,arr4r)

arr3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
 arr4r:
 [[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]



array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])