<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/statistical_f.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Statistical functions/methods

In [1]:
import numpy as np

In [2]:
# creating an array
arr1 = np.arange(1, 13).reshape(3, 4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
# sum() - sum of all elements
# arr1.sum()
np.sum(arr1)

78

In [6]:
# sum of each row and column
sum_r = arr1.sum(axis = 1) # sum of rows
sum_c = arr1.sum(axis = 0) # sum of columns

print(f"sum of each row: {sum_r}\n that of each column: {sum_c}")


sum of each row: [10 26 42]
 that of each column: [15 18 21 24]


In [7]:
# mean()
mean_arr1 = arr1.mean()
mean_arr1

6.5

In [16]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
# cumulative sum of the data
np.cumsum(arr1)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])